#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,vmem=1gb,walltime=0:05:00

set -x

hookdir=$(realpath abcd-spec/hooks)
singularity exec -B $hookdir -e docker://brainlife/dipy:1.1.1 $hookdir/bl2bids.py
singularity exec -B $hookdir -e docker://brainlife/dipy:1.1.1 $hookdir/bl2bids-meeg.py
