#!/bin/bash

#return code 0 = running
#return code 1 = finished successfully
#return code 2 = failed
#return code 3 = unnkown?

if [ ! -z $BRAINLIFE_LOCAL_VALIDATOR ] && [[ "$SERVICE" = brainlife/validator* ]]; then
        `dirname $0`/../direct/stop
        exit $?
fi

set -o pipefail

if [ -f finished ]; then
    echo "already finished"
    exit 1 #success
fi

if [ -f jobid ]; then
    jobid=`cat jobid`
    if [ -z $jobid ]; then
	echo "no jobid?"
        exit 2 #failed
    fi
    #echo "condor_q -long $jobid"
    jobstate=$(condor_q -long $jobid | grep "^JobStatus" | head -1 | cut -d " " -f 3)
    if [ $? -ne 0 ]; then
	echo "condor_q failed($?).. or job no longer exists - guessing status from the timestamp of the last log"
	if [ $(find . -mmin -60 | wc -l) -eq 0 ]; then
		echo "nothing is updated in the last 60 minutes.. failing"
		exit 2 #failed
	else
		echo "files still getting updated... will check again later"
		exit 3 #Unknown
	fi
    fi

#    if [ -z $jobstate ]; then
#	#check the history
#        #echo "condor_history -long $jobid"
#	jobstate=$(condor_history -long $jobid | grep "^JobStatus" | head -1 | cut -d " " -f 3)
#	if [ $? -ne 0 ]; then
#	    echo "job is gone and no finished file exists"
#            exit 2
#	    #echo "condor_history failed.. will check later again"
#	    #exit 3
#	    #echo "condor_history failed.. assuming success"
#	    #exit 1
#	fi
#	if [ -z $jobstate ]; then
#	    echo "couldn't get jobstate.. removed?"
#	    exit 2 #removed?
#	fi
#    fi

    #echo "exitcode $exitcode"
    #echo "jobstate:$jobstate "

	#http://pages.cs.wisc.edu/~adesmet/status.html
	#0	Unexpanded	U
	#1	Idle	I
	#2	Running	R
	#3	Removed	X
	#4	Completed	C
	#5	Held	H
	#6	Submission_err	E

    if [ $jobstate == "0" ]; then
        exit 3
    fi
    if [ $jobstate == "1" ]; then
	echo "waiting for job slot (idle)"
        exit 0
    fi
    if [ $jobstate == "2" ]; then
	#echo "running.."
        logfile=$(ls -rt *.log | tail -1)
        tail -2 $logfile
        exit 0
    fi
    if [ $jobstate == "3" ]; then
	echo "job removed"
        exit 2
    fi
    if [ $jobstate == "4" ]; then
	exitcode=$(condor_history -long $jobid | grep "^ExitCode" | head -1 | cut -d " " -f 3)
	echo "finished with code:$exitcode"
        logfile=$(ls -rt *.log | tail -1)
        tail -2 $logfile
	if [ $exitcode -eq 0 ]; then
		exit 1
	else
		exit 2
	fi
    fi
    if [ $jobstate == "5" ]; then
	echo "job held"
        exit 0
    fi
    if [ $jobstate == "6" ]; then
	echo "submission error"
        exit 2
    fi

    echo "odd.."
    exit 2
fi

echo "can't determine the status!"
exit 3
