#!/bin/bash

#return code 0 = running
#return code 1 = finished successfully
#return code 2 = failed
#return code 3 = unknown (retry later)

if [ ! -f jobid ];then
	echo "no jobid - not yet submitted?"
	exit 1
fi

jobid=`cat jobid`
if [ -z $jobid ]; then
	echo "jobid is empty.. failed to submit?"
	exit 3
fi

jobstate=`squeue -h -j $jobid --Format=statecompact`
if [ -z $jobstate ]; then
	echo "Job removed before completing - maybe timed out?" 
	exit 2
fi
if [ $jobstate == "PD" ]; then
        eststart=`squeue -h -o "%S" -j $jobid`
        echo "Waiting in the queue - estimated start time: $eststart"
	#curl -X POST -H "Content-Type: application/json" -d "{\"msg\":\"Waiting in the PBS queue : $eststart\"}" $PROGRESS_URL
	exit 0
fi
if [ $jobstate == "R" ]; then
	logname="slurm-$jobid.out"
	tail -1 $logname
	exit 0
fi
if [ $jobstate == "F" ]; then
	echo "Job failed"
	exit 2
fi

#assume failed for all other state
echo "unknown state: $jobstate"
exit 3

