#!/bin/bash

#return code 0 = running
#return code 1 = finished successfully
#return code 2 = failed
#return code 3 = unknown (retry later)

if [ ! -f jobid ];then
	echo "no jobid - not yet submitted?"
	exit 1
fi

jobid=`cat jobid`
if [ -z $jobid ]; then
	echo "jobid is empty.. failed to submit?"
	exit 3
fi

jobstate=`scontrol show job $jobid | grep JobState | cut -f4 -d' ' | cut -f2 -d'='`
if [ -z $jobstate ]; then
	echo "no job state.. odd"
	exit 2
fi
if [ $jobstate == "PENDING" ]; then
        eststart=`squeue -h -o "%S" -j $jobid`
        echo "Waiting in the queue - estimated start time: $eststart"
	#curl -X POST -H "Content-Type: application/json" -d "{\"msg\":\"Waiting in the PBS queue : $eststart\"}" $PROGRESS_URL
	exit 0
fi
if [ $jobstate == "RUNNING" ]; then
	logname="slurm-$jobid.log"
	tail -1 $logname
	exit 0
fi
if [ $jobstate == "FAILED" ]; then
	echo "Job failed"
	exit 2
fi
if [ $jobstate == "COMPLETEING" ]; then
	echo "completing"
	exit 0
fi
if [ $jobstate == "COMPLETED" ]; then
	echo "Job finished"
	exit 1
fi

echo "unknown state: $jobstate"
exit 3

