#!/bin/bash

#people often forgets to set exbit on main..
chmod +x main

#to allow restart
rm -f exit-code

echo "nohup-ing main"
nohup time bash -c "smon & smonpid=\$!;
    ./main; 
    echo \$? > exit-code;
    kill \$smonpid" > output.log 2> error.log &
echo $! > pid

