#!/bin/bash

#return code 0 = running
#return code 1 = finished successfully
#return code 2 = failed
#return code 3 = unknown (retry later)

if [ -f exit-code ]
then
	code=$(cat exit-code)
	[ $code -eq 0 ] && exit 1

	#echo "finished with exit code $code"
    logfile=$(ls -rt *.log | tail -1)
    tail -1 $logfile
	exit 2
fi

if [ -f pid ]
then
    if ps -p $(cat pid) > /dev/null
    then
        #get last line of last log touched
        logfile=$(ls -rt *.log | tail -1)
        tail -1 $logfile
        exit 0
    else
        #stopped
        echo "no longer running but didn't finish"
        exit 2
    fi
fi

echo "not yet started?"
exit 3
